### ISSUE TITLE
Annoying transitions when menu has links instead of anchors

### ISSUE THREAD

**Issue by ghost** [archost/alicht#1]
_From @fabienwang on May 27, 2015 13:45_

![annoying_anim](https://cloud.githubusercontent.com/assets/8741873/7837437/314cdf9e-0487-11e5-9b2e-496c9bab53dd.gif)

_Copied from original issue: eliteheberg/elicht#1_

**Comment by fabienwang** [comment]
Will transfer this bug upstream :laughing:

**Comment by nileane** [comment]
I can't reproduce the bug on Alicht anywhere. Hmm?

**Comment by younishd** [comment]
@fabienwang Can you paste the source code somewhere?

**Comment by nileane** [comment]
It's confirmed this only impacts your fork.
