### ISSUE TITLE
new img/ vs old css/img and unused files

### ISSUE THREAD

**Issue by ghost** [archost/alicht#10]
You have put some new backgrounds in img/

Some old backgrounds are still in css/img/ and are not used anymore by the alicht.css file
background.jpg & noise.png

**Comment by younishd** [comment]
@fabienwang
I think this is actually correct.
- `noise.png` may still be used (maybe not everywhere though).
- `/css/img/` contains images that are part of the alicht style, while `/img/` contains sample images that are merely used to demonstrate the cover feature.
- `background.jpg` was the first version of a background image in alicht and is kept for historical reasons. It is also correctly placed in `/css/img/` for the reasons mentioned above.

More generally: the inner structure of alicht (i.e., organization of directories and files) is considered **private** in terms of OO, which means that a user of this framework ought not to worry about these details, as they are hidden from his sight and do not have any functional impact on the framework itself. Therefore, the choice of a meaningful project structure should remain to the developers of alicht.

Nothing to do here.

**Comment by ghost** [comment]
nice bullshit there :+1: it means: Thanks for the explanation in fabienwang's language.
