### ISSUE TITLE
Headings are too close to header

### ISSUE THREAD

**Issue by younishd** [archost/alicht#11]
The `h1` appears too close to the header.

![](http://i.imgur.com/JnAQq0k.png)

This doesn't work…

``` html
<h1>Free price web hosting.</h1>
```

…but this does!?

``` html
<h1 id="lel">Free price web hosting.</h1>
```

**Comment by ghost** [comment]
Yes I noticed the same bug.
I also noticed since the section updates, you do not need any style on the first h1 anymore.
Removing styles do fix the issue.

Thanks for your lecture.

**Comment by younishd** [comment]
Oh, you are right @fabienwang! This worked great for me. :+1:
