### ISSUE TITLE
"Heading" card style

### ISSUE THREAD

**Issue by nileane** [archost/alicht#16]
A new card style, mostly to be used on section.cover, over a background picture.

Its specificities :
- h1, h2, and h3 are aligned to the left with reduced margins
- Buttons are set to the right
- A background-color set to rgba(0, 0, 0, .7) (to be determined).
- No border-radius
- No box-shadow
- No text-shadow
- Only light and normal font weights.

How @younishd and I imagined it: 
![image_2015-10-24_00-58-43](https://cloud.githubusercontent.com/assets/914451/10707575/9bca72fe-79f4-11e5-982a-1ee34137d011.png)

**Comment by younishd** [comment]
![](http://i.memeful.com/media/post/kRp6z2w_700wa_0.gif)
