### ISSUE TITLE
Alerts mess up cover

### ISSUE THREAD

**Issue by younishd** [archost/alicht#23]
When you display a notification on a cover layout it fucks up everything.

![g4m9054mjg954g959mj5994554mg905](https://cloud.githubusercontent.com/assets/994290/10712395/36b2111e-7a9a-11e5-8c76-db54fe3f31a9.png)

**Comment by nileane** [comment]
Not actually a bug, but yup : we need to add a feature to alerts so as to have them appear **over** content.

**Comment by nileane** [comment]
Okay, this is a wontfix. In order to keep things simple, in this case, one only has to insert the alert inside the section.cover element.
